version: '3'
services:
  web:
    build: .
    command: bundle exec pumactl start
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    ports:
      - 3001:3001
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    image: mysql:5.7
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
volumes:
  db-volume:
  bundle:
